version: 2.1

orbs:
  orb-tools: circleci/orb-tools@3.0.0

executors:
  lint-condo:
    resource_class: small
    docker:
      - image: singapore/lint-condo

jobs:
  lint:
    executor: lint-condo
    steps:
      - checkout
      - run: yamllint .

workflows:
  verify:
    jobs:
      - lint
      - orb-tools/publish:
          name: publish
          context: global
          filters:
            branches:
              ignore: master
          orb-path: src/@orb.yml
          orb-ref: entur/owasp@dev:$CIRCLE_BRANCH
      - orb-tools/increment:
          name: release
          context: global
          filters:
            branches:
              only: master
          orb-path: src/@orb.yml
          orb-ref: entur/owasp
          requires:
            - lint
