version: 2.1

description: |
  An orb for running owasp vulnerability checks through gradle or maven

orbs:
  gradle: circleci/gradle@1.0.6

executors:
  default:
    docker:
      - image: circleci/openjdk:11-jdk-sid
        environment:
          TERM: dumb

jobs:
  gradle:
    parameters:
      executor:
        description: The name of custom executor to use
        type: executor
        default: default
      command:
        type: string
        default: dependencyCheckAnalyze
      reportPath:
        type: string
        default: build/reports/*.html
    executor: <<parameters.executor>>
    steps:
      - checkout
      - gradle/with_cache:
          steps:
            - run:
                name: Run Tests
                command: ./gradlew << parameters.command >>
      - gradle/collect_test_results:
          test_results_path: ""
          reports_path: <<parameters.reportPath>>

