version: 2.1

description: |
  An orb for running OWASP vulnerability checks through Gradle

orbs:
  gradle: circleci/gradle@1.0.11
  maven: circleci/maven@0.0.8

executors:
  default:
    docker:
      - image: circleci/openjdk:11-jdk-sid
        environment:
          TERM: dumb

commands:
  restore_owasp_cache:
    steps:
      - restore_cache:
          name: Restore OWASP cache
          keys:
            - cve-cache-{{ checksum "year" }}-{{ checksum "twelveWeeks" }}-{{ checksum "fourWeeks" }}-{{ checksum "week" }}-{{ checksum "day" }}-{{ checksum "twelveHoursOfDay" }}-{{ checksum "fourHoursOfDay" }}
            - cve-cache-{{ checksum "year" }}-{{ checksum "twelveWeeks" }}-{{ checksum "fourWeeks" }}-{{ checksum "week" }}-{{ checksum "day" }}-{{ checksum "twelveHoursOfDay" }}
            - cve-cache-{{ checksum "year" }}-{{ checksum "twelveWeeks" }}-{{ checksum "fourWeeks" }}-{{ checksum "week" }}-{{ checksum "day" }}
            - cve-cache-{{ checksum "year" }}-{{ checksum "twelveWeeks" }}-{{ checksum "fourWeeks" }}-{{ checksum "week" }}
            - cve-cache-{{ checksum "year" }}-{{ checksum "twelveWeeks" }}-{{ checksum "fourWeeks" }}
            - cve-cache-{{ checksum "year" }}-{{ checksum "twelveWeeks" }}
            - cve-cache-{{ checksum "year" }}
            - cve-cache
  store_owasp_cache:
    parameters:
      cve_data_directory:
        type: string
    steps:
      - save_cache:
          name: Save OWASP cache
          key: cve-cache-{{ checksum "year" }}-{{ checksum "twelveWeeks" }}-{{ checksum "fourWeeks" }}-{{ checksum "week" }}-{{ checksum "day" }}-{{ checksum "twelveHoursOfDay" }}-{{ checksum "fourHoursOfDay" }}
          paths:
            - <<parameters.cve_data_directory>>

  generate_cache_keys:
    steps:
      - run:
          name: Generate OWASP cache keys
          command: |
            echo $(date +"%Y") >> year
            echo $(( $(date +"%_j") / 84)) >> twelveWeeks
            echo $(( $(date +"%_j") / 28)) >> fourWeeks
            echo $(( $(date +"%_j") / 7)) >> week
            echo $(( $(date +"%_j"))) >> day
            echo $(( $(date +"%_H") / 12)) >> twelveHoursOfDay
            echo $(( $(date +"%_H") / 4)) >> fourHoursOfDay

  collect_reports:
    description: |
      Store reports to build artifacts and persist to workspace.
    parameters:
      reports_path:
        description: Location of report published
        type: string
    steps:
      - run:
          name: Gather reports
          command: |
            mkdir -p owasp
            cp << parameters.reports_path >>/dependency-check*.* owasp
      - store_artifacts:
          path: owasp
          destination: Reports
      - persist_to_workspace:
          root: .
          paths:
            - owasp

jobs:
  gradle_owasp_dependency_check:
    parameters:
      executor:
        description: The name of custom executor to use
        type: executor
        default: default
      cve_data_directory:
        type: string
        default: "~/.owasp-dependency-check"
      task:
        description: Task name
        type: string
        default: "dependencyCheckAnalyze"
      reportPath:
        type: string
        default: build/reports/
    executor: <<parameters.executor>>
    steps:
      - checkout
      - generate_cache_keys
      - restore_owasp_cache
      - gradle/with_cache:
          steps:
            - run:
                name: Run OWASP Dependency Check using Gradle
                command: ./gradlew <<parameters.task>> --info
      - gradle/collect_test_results:
          test_results_path: ""
          reports_path: <<parameters.reportPath>>
      - store_owasp_cache:
          cve_data_directory: <<parameters.cve_data_directory>>

  maven_owasp_dependency_check:
    parameters:
      executor:
        description: The name of custom executor to use
        type: executor
        default: default
      cve_data_directory:
        type: string
        default: "~/.owasp-dependency-check"
      task:
        description: Task name
        type: string
        default: "check"
      reportPath:
        type: string
        default: target/owasp-reports
      settings_file:
        description: Specify a custom settings file to use (optional)
        type: string
        default: ""
    executor: <<parameters.executor>>
    steps:
      - checkout
      - generate_cache_keys
      - restore_owasp_cache
      - maven/with_cache:
          settings_file: << parameters.settings_file >>
          steps:
            - run:
                name: Run OWASP Dependency Check using Maven
                command: mvn org.owasp:dependency-check-maven:<<parameters.task>>
      - collect_reports:
          reports_path: <<parameters.reportPath>>
      - store_owasp_cache:
          cve_data_directory: <<parameters.cve_data_directory>>

