version: 2.1

description: |
  An orb for running OWASP vulnerability checks through Gradle and Maven.
  Reports are persisted as artifacts under the directory 'Report/OWASP'.
  Source: https://github.com/entur/owasp-orb

examples:
  standard_gradle_project:
    description: |
      If you have a standard Gradle project, you can use this orb to run through
      a common Gradle worklow.
    usage:
      version: 2.1

      orbs:
        owasp: entur/owasp@0.0.3

      workflows:
        owasp:
          jobs:
            - owasp/gradle_owasp_dependency_check:
                executor: java_11
                context: global

  standard_maven_project:
    description: |
      If you have a standard Maven project, you can use this orb to run through
      a common Gradle worklow.
    usage:
      version: 2.1

      orbs:
        owasp: entur/owasp@0.0.3

      workflows:
        owasp:
          jobs:
            - owasp/maven_owasp_dependency_check:
                executor: java_11
                context: global

orbs:
  gradle: circleci/gradle@1.0.11
  maven: circleci/maven@0.0.8

executors:
  default:
    docker:
      - image: circleci/openjdk:11-jdk-sid
        environment:
          TERM: dumb

aliases:
  - &gradle_owasp_dependency_check
    parameters:
      executor:
        description: The name of custom executor to use
        type: executor
        default: default
      cve_data_directory:
        type: string
        default: "~/.owasp-dependency-check"
      task:
        description: Task name
        type: string
        default: "dependencyCheckAnalyze"
      reportPath:
        description: Report directory (no trailing slash).
        type: string
        default: build/reports
    executor: <<parameters.executor>>
    steps:
      - checkout
      - generate_cache_keys
      - restore_owasp_cache
      - gradle/with_cache:
          steps:
            - run:
                name: Run OWASP Dependency Check using Gradle
                command: ./gradlew <<parameters.task>> --info
      - collect_reports:
          reports_path: <<parameters.reportPath>>
      - store_owasp_cache:
          cve_data_directory: <<parameters.cve_data_directory>>


commands:
  restore_owasp_cache:
    steps:
      - restore_cache:
          name: Restore OWASP cache
          keys:
            - cve-cache-{{ checksum "/tmp/year" }}-{{ checksum "/tmp/twelveWeeks" }}-{{ checksum "/tmp/fourWeeks" }}-{{ checksum "/tmp/week" }}-{{ checksum "/tmp/day" }}-{{ checksum "/tmp/twelveHoursOfDay" }}-{{ checksum "/tmp/fourHoursOfDay" }}
            - cve-cache-{{ checksum "/tmp/year" }}-{{ checksum "/tmp/twelveWeeks" }}-{{ checksum "/tmp/fourWeeks" }}-{{ checksum "/tmp/week" }}-{{ checksum "/tmp/day" }}-{{ checksum "/tmp/twelveHoursOfDay" }}
            - cve-cache-{{ checksum "/tmp/year" }}-{{ checksum "/tmp/twelveWeeks" }}-{{ checksum "/tmp/fourWeeks" }}-{{ checksum "/tmp/week" }}-{{ checksum "/tmp/day" }}
            - cve-cache-{{ checksum "/tmp/year" }}-{{ checksum "/tmp/twelveWeeks" }}-{{ checksum "/tmp/fourWeeks" }}-{{ checksum "/tmp/week" }}
            - cve-cache-{{ checksum "/tmp/year" }}-{{ checksum "/tmp/twelveWeeks" }}-{{ checksum "/tmp/fourWeeks" }}
            - cve-cache-{{ checksum "/tmp/year" }}-{{ checksum "/tmp/twelveWeeks" }}
            - cve-cache-{{ checksum "/tmp/year" }}
            - cve-cache
  store_owasp_cache:
    parameters:
      cve_data_directory:
        type: string
    steps:
      - save_cache:
          name: Save OWASP cache
          key: cve-cache-{{ checksum "/tmp/year" }}-{{ checksum "/tmp/twelveWeeks" }}-{{ checksum "/tmp/fourWeeks" }}-{{ checksum "/tmp/week" }}-{{ checksum "/tmp/day" }}-{{ checksum "/tmp/twelveHoursOfDay" }}-{{ checksum "/tmp/fourHoursOfDay" }}
          paths:
            - <<parameters.cve_data_directory>>

  generate_cache_keys:
    steps:
      - run:
          name: Generate OWASP cache keys
          command: |
            echo $(date +"%Y") >> /tmp/year
            echo $(( $(date +"%_j") / 84)) >> /tmp/twelveWeeks
            echo $(( $(date +"%_j") / 28)) >> /tmp/fourWeeks
            echo $(( $(date +"%_j") / 7)) >> /tmp/week
            echo $(( $(date +"%_j"))) >> /tmp/day
            echo $(( $(date +"%_H") / 12)) >> /tmp/twelveHoursOfDay
            echo $(( $(date +"%_H") / 4)) >> /tmp/fourHoursOfDay

  collect_reports:
    description: |
      Store reports to build artifacts and persist to workspace.
    parameters:
      reports_path:
        description: Location of report published
        type: string
      persist_to_workspace:
        description: Persist reports to workspace
        type: boolean
        default: true
    steps:
      - run:
          name: Gather reports
          command: |
            mkdir -p OWASP
            cp << parameters.reports_path >>/dependency-check*.* OWASP
      - store_artifacts:
          path: OWASP
          destination: Reports/OWASP
      - when:
          condition: <<parameters.persist_to_workspace>>
          steps:
            - persist_to_workspace:
                root: .
                paths:
                  - OWASP

jobs:
  owasp_dependency_check: *gradle_owasp_dependency_check # default to gradle
  gradle_owasp_dependency_check: *gradle_owasp_dependency_check
  maven_owasp_dependency_check:
    parameters:
      executor:
        description: The name of custom executor to use
        type: executor
        default: default
      cve_data_directory:
        type: string
        default: "~/.owasp-dependency-check"
      task:
        description: Task name
        type: string
        default: "check"
      reportPath:
        type: string
        default: target/owasp-reports
      settings_file:
        description: Specify a custom settings file to use (optional)
        type: string
        default: ""
    executor: <<parameters.executor>>
    steps:
      - checkout
      - generate_cache_keys
      - restore_owasp_cache
      - maven/with_cache:
          settings_file: << parameters.settings_file >>
          steps:
            - run:
                name: Run OWASP Dependency Check using Maven
                command: mvn org.owasp:dependency-check-maven:<<parameters.task>>
      - collect_reports:
          reports_path: <<parameters.reportPath>>
      - store_owasp_cache:
          cve_data_directory: <<parameters.cve_data_directory>>

